@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant Server
participant ClientB

ClientA->Server:残り時間を送信(開始から)
note left:一番最初に入室した人が\n残り時間をカウントする\nマスタークライアント方式
ClientB<-Server:残り時間を送信

ClientA->Server:残り時間を送信(0秒)
ClientA<-Server:時間切れを通知
ClientB<-Server:時間切れを通知

ClientA->Server:退出
ClientB->Server:退出

@enduml
