@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant Server
participant RoomData
participant ClientB

ClientA->Server:入室
ClientB->Server:入室

ClientA<-Server:全員集まった
ClientB<-Server:全員集まった

ClientA->RoomData:準備完了を保存
ClientB->RoomData:準備完了を保存

ClientA<-Server:ゲーム開始
ClientB<-Server:ゲーム開始

@enduml
