@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant MagicOnion
participant ClientB
participant RoomData

ClientA->MagicOnion:Move(A,pos)
MagicOnion->RoomData:位置更新を保存
ClientB<-MagicOnion:OnMove(A,pos)

@enduml
