@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant ClientB
participant ClientC
participant MagicOnion

ClientA->MagicOnion:Join(A)
ClientA<-MagicOnion:Users(A)
ClientB->MagicOnion:Join(B)
ClientA<-MagicOnion:OnJoin(B)
ClientB<-MagicOnion:Users(A,B)

@enduml
