@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant MagicOnion
participant ClientB
participant ClientC

ClientA->MagicOnion:Join(A)
ClientA<-MagicOnion:Users(A)
ClientB->MagicOnion:Join(B)
ClientA<-MagicOnion:OnJoin(B)
ClientB<-MagicOnion:Users(A,B)

@enduml
