@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant ClientB
participant Server
participant DB

ClientA->Server:ロビーに入室
note over Server:同じマッチング条件の\n人が集まったか判定

ClientB->Server:ロビーに入室
ClientA<-Server:入室したことを通知
note over Server:同じマッチング条件の\n人が集まったか判定。
note over Server:集まったらルーム名決定

note over ClientA,ClientB:一覧表示を更新

Server->DB:対戦情報を登録する
note over DB:レコードを追加する

Server<-DB:テーブルのidを送信する
ClientA<-Server:マッチング完了
note left:インゲームのルーム名を\nサーバーから受け取る
ClientB<-Server:マッチング完了
note left:インゲームのルーム名を\nサーバーから受け取る

ClientA->Server:ロビーから退出
ClientB->Server:ロビーから退出
note over ClientB:インゲームのシーンに移動

ClientA->Server:受け取ったルーム名のルームに入室
ClientB->Server:受け取ったルーム名のルームに入室

note across:インゲーム開始

@enduml
