@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant MagicOnion
participant ClientB



loop
   ClientB->MagicOnion:移動
   note right:入室後に\n一定間隔で送信
   note over MagicOnion:位置を更新して、\nRoomDataに保存
   ClientA<-MagicOnion:Bの移動
end

@enduml
