@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant Server
participant RoomData
participant ClientB

ClientA->Server:移動
Server->RoomData:位置更新を保存
ClientB<-Server:Aが移動したことを送信

@enduml
