@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant Server
participant ClientB

ClientA->Server:入室
ClientB->Server:入室
note over Server:全員揃ったか判定

ClientA<-Server:全員集まった
note over ClientA:開始前演出
ClientB<-Server:全員集まった
note over ClientB:開始前演出

ClientB->Server:準備完了
note over Server:全員準備できたか判定
ClientA->Server:準備完了
note over Server:全員準備できたか判定

ClientA<-Server:ゲーム開始
ClientB<-Server:ゲーム開始

@enduml
