@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ClientA
participant Server
participant ClientB
participant ClientC

ClientA->Server:Join(A)
ClientA<-Server:Users(A)
ClientB->Server:Join(B)
ClientA<-Server:OnJoin(B)
ClientB<-Server:Users(A,B)

@enduml
